In [25]:
# import pandas, sklearn, plotly
from sklearn.datasets import fetch_openml

# import plotly
import chart_studio.plotly as py
import cufflinks as cf
cf.go_offline(connected=True)

# import pandas
import pandas as pd


In [24]:
mnist = fetch_openml('mnist_784')
mnist

{'data':        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
 0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 ...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
 69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 
      

In [161]:
X, y = mnist["data"], mnist["target"]

pandas.core.frame.DataFrame

In [21]:
X.shape

(70000, 784)

In [17]:
y.shape

(70000,)

In [28]:
X.describe
X.head

<bound method NDFrame.head of        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0  

In [29]:
X.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [30]:
X.shape

(70000, 784)

In [31]:
X.sample()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
44099     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
44099      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
44099       0.0       0.0       0.0       0.0       0.0  

[1 rows x 784 columns]

In [35]:
X.isnull()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       False   False   False   False   False   False   False   False   False   
1       False   False   False   False   False   False   False   False   False   
2       False   False   False   False   False   False   False   False   False   
3       False   False   False   False   False   False   False   False   False   
4       False   False   False   False   False   False   False   False   False   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995   False   False   False   False   False   False   False   False   False   
69996   False   False   False   False   False   False   False   False   False   
69997   False   False   False   False   False   False   False   False   False   
69998   False   False   False   False   False   False   False   False   False   
69999   False   False   False   False   False   False   False   False   False   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0        False  ...     False     False     False     False     False   
1        False  ...     False     False     False     False     False   
2        False  ...     False     False     False     False     False   
3        False  ...     False     False     False     False     False   
4        False  ...     False     False     False     False     False   
...        ...  ...       ...       ...       ...       ...       ...   
69995    False  ...     False     False     False     False     False   
69996    False  ...     False     False     False     False     False   
69997    False  ...     False     False     False     False     False   
69998    False  ...     False     False     False     False     False   
69999    False  ...     False     False     False     False     False   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0         False     False     False     False     False  
1         False     False     False     False     False  
2         False     False     False     False     False  
3         False     False     False     False     False  
4         False     False     False     False     False  
...         ...       ...       ...       ...       ...  
69995     False     False     False     False     False  
69996     False     False     False     False     False  
69997     False     False     False     False     False  
69998     False     False     False     False     False  
69999     False     False     False     False     False  

[70000 rows x 784 columns]

In [39]:
mnist.data

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69995       0.0       0.0       0.0       0.0       0.0  
69996       0.0       0.0       0.0       0.0       0.0  
69997       0.0       0.0       0.0       0.0       0.0  
69998       0.0       0.0       0.0       0.0       0.0  
69999       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [189]:
some_digit = X.iloc[[36000]]
some_digit_image = some_digit.to_numpy().reshape((28,28))

In [190]:
some_digit.to_numpy()

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0., 

In [191]:
import plotly.express as px
import numpy as np

fig = px.imshow(some_digit_image)
fig.show()

In [180]:
y[36000]

'9'

In [70]:
# train_test_split
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [83]:
# shuffle row index
X_train.sample(frac=1, random_state=42)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
12628     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
37730     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
39991     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8525      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8279      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
54343     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
38158     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
860       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
15795     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56422     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
12628      0.0  ...       0.0       0.0       0.0       0.0       0.0   
37730      0.0  ...       0.0       0.0       0.0       0.0       0.0   
39991      0.0  ...       0.0       0.0       0.0       0.0       0.0   
8525       0.0  ...       0.0       0.0       0.0       0.0       0.0   
8279       0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
54343      0.0  ...       0.0       0.0       0.0       0.0       0.0   
38158      0.0  ...       0.0       0.0       0.0       0.0       0.0   
860        0.0  ...       0.0       0.0       0.0       0.0       0.0   
15795      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56422      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
12628       0.0       0.0       0.0       0.0       0.0  
37730       0.0       0.0       0.0       0.0       0.0  
39991       0.0       0.0       0.0       0.0       0.0  
8525        0.0       0.0       0.0       0.0       0.0  
8279        0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
54343       0.0       0.0       0.0       0.0       0.0  
38158       0.0       0.0       0.0       0.0       0.0  
860         0.0       0.0       0.0       0.0       0.0  
15795       0.0       0.0       0.0       0.0       0.0  
56422       0.0       0.0       0.0       0.0       0.0  

[60000 rows x 784 columns]

In [192]:
y_train.sample(frac=1, random_state=42)

12628    7
37730    3
39991    8
8525     9
8279     3
        ..
54343    3
38158    8
860      0
15795    0
56422    4
Name: class, Length: 60000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [193]:
# model for predicting only '9' character
y_train_9 = (y_train == '9')
y_test_9 = (y_test == '9')

In [194]:
# using SGD classifier
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter = 5, random_state=42)
sgd_clf.fit(X_train, y_train_9)

C:\Users\rlarj\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:574: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.



SGDClassifier(max_iter=5, random_state=42)

In [198]:
sgd_clf.predict(some_digit)

array([False])

In [196]:
# cross val score
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, X_train, y_train_9, cv=3, scoring="accuracy")

C:\Users\rlarj\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:574: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.

C:\Users\rlarj\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:574: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.

C:\Users\rlarj\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:574: ConvergenceWarning:

Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.



array([0.94695, 0.94565, 0.9516 ])

In [203]:
from sklearn.base import BaseEstimator

class Never5Classifier(BaseEstimator):
    def fit(self, X, y=None):
        pass
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

In [204]:
never_5_clf = Never5Classifier()
cross_val_score(never_5_clf, X_train, y_train_5, cv=3, scoring="accuracy")

array([0.8993 , 0.8999 , 0.90335])